
# Mineru PDF Extrator
MINERU_JSON_FILE_EXTENSION = "_content_list.json"
DEFAULT_MINERU_FOLDER = "./mineru"

# CHUNKS
MAX_CHUNK_SIZE = 2000
OVERLAP_CHAR_SIZE = 200

# Summerizer
MAX_INPUT_CHAR = 6000 # Taille max d'entrée
MAX_REQUEST_TOKENS = 2048 # Taille max de sortie
MAX_SUMMARY_ATTEMPTS = 2
MAX_TIMEOUT_IN_SEC = 1.5
OLLAMA_MODEL_SUMMARY = "llama3"

# LLM : Ollama Model
OLLAMA_MODEL_BASE = "qwen3"
OLLAMA_URL = "http://localhost:11434"
LLM_REQUEST_TIMEOUT_IN_SEC = 120.0

LLM_TEMPERATURE = 0.2
LLM_TOP_P = 0.95
LLM_NUM_CONTEXT = 8192
LLM_CLIENT_CONNECTION_KEEPALIVE = "5m"
LLM_MAX_ATTEMPTS = 2
LLM_QWEN_THINKING = False
